# Generated by Django 5.1.4 on 2025-02-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_num_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='num_available',
            field=models.IntegerField(default=1),
        ),
    ]
